#!/bin/bash
#echo "$(dirname "$1")"
#echo "$(basename "$1")"
xpath=${1%/*}
xbase=${1##*/}
xfext=${xbase##*.}
xpref=${xbase%.*}

getsub ${1}

#echo;echo path=${xpath};echo pref=${xpref};echo ext=${xfext}
nfr="${xpath}/${xpref}.fra.srt"
nen="${xpath}/${xpref}.eng.srt"
n="${xpath}/${xpref}.srt"
#echo $nfr;echo $nen;echo $n
s=""
if [ -f "${n}" ]; then
    s=" --subtitles \"${n}\" "
fi
if [ -f "${nen}" ]; then
    s=" --subtitles \"${nen}\" "
fi
if [ -f "${nfr}" ]; then
    s=" --subtitles \"${nfr}\" "
fi
to=""
#echo ${xfext}
if [[ ${xfext,,} == "avi" ]]; then
    to=" --tomp4 " 
fi
launch="sudo castnow \"${1}\" ${to} ${s}"
#echo $launch
eval "$launch"
echo "fin"
